import Footer from "@/components/layout/footer/Footer";
import Header from "@/components/layout/header/Header";
import type { Metadata } from "next";
import { Playfair_Display, Urbanist, Geist } from "next/font/google";
import "./globals.css";

// Fonts - Optimized for performance
const titleFont = Urbanist({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--title-font",
  display: "swap",
  preload: true,
  fallback: ["system-ui", "arial"],
});

// Highlight font for Hero
const highlightFont = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--highlight-font",
  display: "swap",
  preload: true,
  fallback: ["serif"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import AnimatedBackground from "@/components/common/AnimatedBackground";

// ... existing imports

import { ModalProvider } from "@/context/ModalContext";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});


// ... existing imports

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", geist.variable)}>
      <body
        className={`${titleFont.variable} ${highlightFont.variable} antialiased bg-[#040810] text-[#e3e3e3]`}
      >
        <ModalProvider>
          <div className="flex flex-col min-h-screen overflow-x-hidden w-full relative">
            <AnimatedBackground />
            <Header />
            <main className="flex-grow">
              {children}
            </main>
            <div className="p-3 w-full max-w-full">
              <Footer />
            </div>
          </div>
        </ModalProvider>
      </body>
    </html>
  );
}
