import Footer from "@/components/layout/footer/Footer";
import Header from "@/components/layout/header/Header";
import type { Metadata } from "next";
import { Playfair_Display, Urbanist } from "next/font/google"; // remove Poppins
import "./globals.css";

// Fonts - Optimized for performance
const titleFont = Urbanist({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--title-font",
  display: "swap",
  preload: true,
  fallback: ["system-ui", "arial"],
});

// Highlight font for Hero
const highlightFont = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--highlight-font",
  display: "swap",
  preload: true,
  fallback: ["serif"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import AnimatedBackground from "@/components/common/AnimatedBackground";

// ... existing imports

import { ModalProvider } from "@/context/ModalContext";

// ... existing imports

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${titleFont.variable} ${highlightFont.variable} antialiased`}
      >
        <ModalProvider>
          <AnimatedBackground />
          <Header />
          {children}
          <div className="p-3">
            <Footer />
          </div>
        </ModalProvider>
      </body>
    </html>
  );
}
